server:
  port: 8082

spring:
  application:
    name: auth-service

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      fail-fast: false

  main:
    allow-bean-definition-overriding: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto


  datasource:
    url: jdbc:mysql://localhost:3306/auth_service_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=True&useSSL=False
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.sakurahino.authservice: DEBUG

google:
  client:
    id: ${GOOGLE_TOKEN}