server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<remaining>.*),/auth/${remaining}

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<remaining>.*),/users/${remaining}

        - id: lesson-service-user
          uri: lb://lesson-service
          predicates:
            - Path=/user/lesson/**
          filters:
            - RewritePath=/user/lesson/(?<remaining>.*),/user/lesson/${remaining}

        - id: lesson-service-admin
          uri: lb://lesson-service
          predicates:
            - Path=/admin/lesson/**
          filters:
            - RewritePath=/admin/lesson/(?<remaining>.*),/admin/lesson/${remaining}

        - id: toppic-service-user
          uri: lb://toppic-service
          predicates:
            - Path=/user/toppic/**
          filters:
            - RewritePath=/user/toppic/(?<remaining>.*),/user/toppic/${remaining}

        - id: toppic-service-admin
          uri: lb://toppic-service
          predicates:
            - Path=/admin/toppic/**
          filters:
            - RewritePath=/admin/toppic/(?<remaining>.*),/admin/toppic/${remaining}

        - id: exam-service-user
          uri: lb://exam-service
          predicates:
            - Path=/user/exam/**
          filters:
            - RewritePath=/user/exam/(?<remaining>.*),/user/exam/${remaining}

        - id: exam-service-admin
          uri: lb://exam-service
          predicates:
            - Path=/admin/exam/**
          filters:
            - RewritePath=/admin/exam/(?<remaining>.*),/admin/exam/${remaining}
jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
