server:
  port: 8087
spring:
  application:
    name: aphabet-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 10000
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      fail-fast: false

  main:
    allow-bean-definition-overriding: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto

  datasource:
    url: jdbc:mysql://localhost:3306/alphabet-service_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: signserver
    password: signserver
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

upload-service:
  base-url: ${UPLOAD_SERVICE_BASE_URL:http://localhost:8081/api/v1/files}

logging:
  level:
    root: INFO
    com.sakurahino.learningservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql: TRACE