server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service_db
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: sakurahino123456789012345678901234
  expiration: 86400000 # 1 ngày

