server:
  port: 8085

spring:
  application:
    name: upload-service
  servlet: # Thêm phần này vào dưới 'spring:'
    multipart:
      max-file-size: 10MB   # Ví dụ: cho phép mỗi file lên đến 10 MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gcp:
      project-id: sakuranihongo-200e5
      credentials:
        location: classpath:credentials/sakuranihongo-200e5-fd43217e81bb.json

gcp:
  storage:
    bucket-name:  sakuranihongo-200e5.firebasestorage.app

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    root: INFO
    com.sakurahino.uploadservice: DEBUG
