server:
  port: 8085

spring:
  application:
    name: result-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/result_service_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    packages-to-scan: com.sakurahino.lessonservice.entity

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  cloud:
    gcp:
      project-id: sakuranihongo-200e5
      credentials:
        location: file:///D:/DATN/keys/sakuranihongo-200e5-fd43217e81bb.json

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    org.springframework.security: DEBUG
    com.sakurahino.resultservice: DEBUG

gcp:
  storage:
    bucket-name: sakuranihongo-200e5.firebasestorage.app